Desktop version: Complete the desktop version of my portfolio website using media queries.
ClaudiaRojasSoto/portfolio_1 pull request #4
Opened 2023-05-03 22:05 UTC by ClaudiaRojasSoto

Complete the desktop version of my portfolio website using media queries, while following best practices for HTML/CSS and using a combination of Grid and Flexbox to lay out the elements on the page. The main goal is to replicate the design from the Figma template as much as possible and create an adaptable UI through the analysis of the Figma design.

Details:

- It uses media queries to ensure the website displays correctly on desktop screens.
- It uses a combination of Grid and Flexbox to style the page elements.
- Reproduces the Figma template design as closely as possible, including font, colors, images, text, and margins.
- Follow best practices for HTML/CSS and ensure no linter errors.
- Document work professionally.
- Implements a responsive UI through analysis of Figma's design.
- Use the correct GitHub flow.

I appreciate in advance your comments and suggestions to improve my work. I remain attentive to your observations. Thank you!

2023-05-03 23:07 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @ClaudiaRojasSoto, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃
 
Meanwhile, you did very well 👏🏾 on this project because your mobile design is intact.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 23:07 UTC, bobb-Rob commented on index.html
> +
Your project is very beautiful and well-structured. But I see a few things that can be done to further improve on it. 

- [x] In the contact section, if you look at the Figma design, the background Illustrations are different for mobile and desktop. But in your project design, you still have the same `background-image: url('your-mobile-image-path')`. I suggest you use media queries to add the different illustrations according to the view. Please fix this. 

Figma design
![image](https://user-images.githubusercontent.com/84156714/236066592-23ab5b89-1c72-4b0f-a509-027dd4bc0567.png)

2023-05-03 23:07 UTC, bobb-Rob commented on index.html
> +        <div class="aboutme-desktop">
- [x] In the About Me section, there are two columns, the one on the left has the `About Me` text and the one on the right has the `languages-framework-skills`. If you look closely at the Figma design, you will see that the left column covers about 40% of the available space and the right column has 60%.  But in your design, it is almost 50-50 columns. In the image below labeled `your design` has a green `X` on it, that red circle shows the part that should be moved slightly to the left. Kindly fix this as you should stick to the design as much as possible. 

Figma Design
![image](https://user-images.githubusercontent.com/84156714/236066944-ba827a2c-df41-4697-b602-402e8d0f1a9e.png)

Your design
![image](https://user-images.githubusercontent.com/84156714/236067077-723fb00a-0ab6-43e3-9484-3547b2436c0d.png)

2023-05-03 23:07 UTC, bobb-Rob commented on index.html
> +            <p class="content-card4">
- [ ] Your project cards look great and the button hover effect works just as expected, well done 👏🏾; But the card container also has a hover effect on it. In the Figma image below 👇🏾 , I have placed three labels `A`, `B`, and `C`. The `A` mark shows the cursor pointer hovering on the project card, and the `B` mark shows the blue border and shadow effect on it as a result of the mouse hover. Then `B` mark is the normal card when the mouse is NOT hovering on it. 

Kindly implement this.

Figma Design
![image](https://user-images.githubusercontent.com/84156714/236068236-13a2f280-1a1f-44e3-9172-efbdde8a601a.png)

2023-05-03 23:07 UTC, bobb-Rob commented on index.html
> +                </ul>
- [ ] Also, please see the `background-image` of the headline section and ensure you use the correct illustration for the desktop from the Figma Design. Again, you can use media query for this. Kindly attach the correct illustration for the correct view.

2023-05-04 01:07 UTC, Olamarx approved these changes
Hi @ClaudiaRojasSoto, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media0.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>
## Highlights
- Linters passed ✔️
- Readme file professional ✔️
## Optional suggestions
- [OPTIONAL] Kindly fix your MIT link, it goes to 404 page.
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 01:22 UTC, merged